services:
  controller:
    build:
      context: ..
      dockerfile: controller/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ADMIN_API_KEY: ${ADMIN_API_KEY}
      AGENT_API_KEY: ${AGENT_API_KEY}
      GIN_MODE: debug
      DATABASE_URL: ${DATABASE_URL}
      PORT: 8080

